#!/usr/bin/env php
<?php
/**
 * PhpDocumentor is a JavaDoc-like documentation tool for PHP.
 *
 * @category  ToolsAndUtilities
 * @package   PhpDocumentor
 * @author    PhpDocumentor Team
 * @copyright 2010 PhpDocumentor Team
 * @license   http://www.opensource.org/licenses/bsd-license.php BSD
 * @filesource
 * @link      http://www.phpdoc.org
 * @link      http://pear.php.net/PhpDocumentor
 */

// TODO: Need to check include path if the class loader if it does not exist relative to this file.

if (is_file(__DIR__ . '/php/pear2/Autoload.php')) {
	include __DIR__ . '/php/pear2/Autoload.php';
}

try {
	$testFile = __DIR__ . '/php/pear2/PhpDocumentor/Resource.php';

	$tokenizer = new \pear2\PhpDocumentor\Tokenizer();
	$resource = $tokenizer->toResource($testFile);
} catch (\Exception $e) {
	echo '*** Fatal Error: ' . $e->getMessage() . "\n\n";
}

?>
