#!/usr/bin/env php
<?php
/**
 * PhpDocumentor is a JavaDoc-like documentation tool for PHP.
 *
 * @category	ToolsAndUtilities
 * @package		phpDocumentor2
 * @subpackage	cli
 * @author    	James Logsdon
 * @copyright 	2010 phpDocumentor2 Team
 * @license   	http://www.opensource.org/licenses/bsd-license.php BSD
 * @link      	http://www.github.com/mfacenet/phpdocumentor
 */

// TODO: Need to check include path if the class loader if it does not exist relative to this file.

if (is_file(__DIR__ . '/php/pear2/Autoload.php')) {
	include __DIR__ . '/php/pear2/Autoload.php';
}

try {
	$testFile = __DIR__ . '/php/pear2/PhpDocumentor/Resource.php';
} catch (\Exception $e) {
	echo '*** Fatal Error: ' . $e->getMessage() . "\n\n";
}

?>
